#日志表
drop table if exists G_CLIENT_LOG;
create table G_CLIENT_LOG
(
  LOG_ID            BIGINT not null  AUTO_INCREMENT,
  USER_ID           VARCHAR(12),
  USER_NAME         VARCHAR(150),
  CLIENT_IP         VARCHAR(16),
  OPERATE_CODE        VARCHAR(20),
  OPERATE_TYPE        VARCHAR(2),  
  OPERATE_STATUS      VARCHAR(2),  
  OPERATE_SERIAL_NO   VARCHAR(21),
  ERROR_CODE        VARCHAR(7),
  ERROR_DESCRIPTION VARCHAR(512),
  LOGON_WAY         VARCHAR(1),
  CHANNEL_TYPE      VARCHAR(1),
  OPERATE_TIME      timestamp(14),
  PRIMARY KEY  (`LOG_ID`)
)ENGINE=InnoDB DEFAULT CHARSET=gb2312;
alter table G_CLIENT_LOG AUTO_INCREMENT=10000;

commit;



#写操作日志的存储过程
DROP PROCEDURE  if exists G_CLIENT_LOG_PROC;

create procedure G_CLIENT_LOG_PROC(in IN_USER_ID varchar(12),

in IN_USER_NAME varchar(150),		
in IN_CLIENT_IP varchar(16),
in IN_OPERATE_CODE varchar(20),
in IN_OPERATE_TYPE varchar(2),
in IN_OPERATE_STATUS varchar(2),

in IN_OPERATE_SERIAL_NO varchar(21),
in IN_ERROR_CODE varchar(7),
in IN_ERROR_DESCRIPTION varchar(512),
in IN_LOGON_WAY varchar(1),
in IN_CHANNEL_TYPE varchar(1),

out OUT_RETCODE VARCHAR(4),
out OUT_RETMESSAGE VARCHAR(140)
)
BEGIN
	/*
	--DECLARE EXIT HANDLER FOR SQLSTATE '23000' set OUT_RETCODE = '-1';
	--DECLARE EXIT HANDLER FOR SQLWARNING,NOT FOUND,SQLEXCEPTION set OUT_RETCODE='-1';
	
	--DECLARE exit HANDLER FOR SQLEXCEPTION BEGIN END;
	--DECLARE exit HANDLER FOR SQLWARNING BEGIN END;
	--DECLARE exit HANDLER FOR NOT FOUND BEGIN END;
	*/
	
	insert into G_CLIENT_LOG(
	USER_ID,
	
	USER_NAME,
	CLIENT_IP,
	OPERATE_CODE,
	OPERATE_TYPE,
	OPERATE_STATUS,
	
	OPERATE_SERIAL_NO,
	ERROR_CODE,
	ERROR_DESCRIPTION,
	LOGON_WAY,
	CHANNEL_TYPE
	) values(
	IN_USER_ID,
	
	IN_USER_NAME,
	IN_CLIENT_IP,
	IN_OPERATE_CODE,
	IN_OPERATE_TYPE,
	IN_OPERATE_STATUS,
	
	IN_OPERATE_SERIAL_NO,
	IN_ERROR_CODE,
	IN_ERROR_DESCRIPTION,
	IN_LOGON_WAY,
	IN_CHANNEL_TYPE
	);

	set OUT_RETCODE='0';
	set OUT_RETMESSAGE='db log success';
	
	commit;
END;
--commit;



/**

DECLARE exit HANDLER FOR SQLSTATE '23000'
delimiter //

CREATE PROCEDURE TEST()
BEGIN
DECLARE exit HANDLER FOR SQLEXCEPTION,SQLWARNING,NOT FOUND
begin
rollback;
insert into bb values('error');
end;
START TRANSACTION;
INSERT INTO aa VALUES (1);
INSERT INTO aa VALUES (2);
COMMIT;
END;
//
CALL test()//


*/